### ISSUE TITLE
`Buf::is_empty()` can return false for an empty buffer

### ISSUE THREAD

**Issue by danburkert** [tailhook/netbuf#12]
`Buf::is_empty` assumes that an empty buffer will never have allocated space, but this assumption is broken by `Buf::read_from` when attempting the read returns an error.

**Comment by tailhook** [comment]
Wow! Thanks for the report. I'll review all buffer allocations shortly.

The idea that when a buffer has no bytes there is no allocated chunk of memory is fundamental to this implementation: we want to avoid having a useless allocated buffer chunk on keep-alive connections. So we have to fix it the hard way, rather than just looking at `.len()`.

**Comment by tailhook** [comment]
Fixed and published as `v0.3.8`. I've reviewed other mutators and it seems others are fine.

Thanks for the report!

**Comment by danburkert** [comment]
Great, thanks!
