### ISSUE TITLE
Remove MAX_BUF_SIZE limitations

### ISSUE THREAD

**Issue by alreece45** [tailhook/netbuf#13]
I'm currently working on a AMQP client, the maximum theoretical size for a frame is 2^32-- slightly over what netbuf allows.

I was thinking of writing a fix, but am wondering on what would be the most acceptable solution.

1. 2 structures, Buf and UnboundBuf-- UnboundBuf does most of the work, but Buf ensures that the capacity remains less than MAX_BUF_SIZE.
2. Like above, but instead of hard-coding the maximum buffer size, have it configurable.
3. 1 structure, but the functionality of MAX_BUF_SIZE toggled off with a feature (or toggled on by removing a default feature).

Thoughts?

**Comment by tailhook** [comment]
Well, I have two contradictory thoughts:
1. While it's possible to have 4GiB message, do they happen in practice? If I would write a server I would limit request to 100MiB or less.
2. This limit is artificial and was made to make netbuf structure 8 bytes smaller. So every keep-alive connection could save 16 bytes in rotor. In rotor-http it saved about 5% memory. When using tokio-core I don't think that even 5% will be saved as tokio structures are quite large.

So I'm keen to drop the limitation and use the full usize range for buffers.

**Comment by alreece45** [comment]
Removing it would be a simple solution, but the buffer size may grow a bit quicker than expected (reserve seems to want 2x the buffer size, when its under the limit). There's also a potential advantage allowing users to use smaller structures when allowed. Even in my use-case, u32/4GiB would be sufficent.

Would it be worth exploring to see if generics/traits could be used to allow more flexibility, but keeping the runtime cost low? Is there a better way to handle a full buffer than to panic? Perhaps return an io::Error, like ErrorKind::InvalidInput or ErrorKind::Other? It looks like a message could be included.

**Comment by tailhook** [comment]
>  but the buffer size may grow a bit quicker than expected (reserve seems to want 2x the buffer size, when its under the limit)

You don't have to be concerned about that. If you already have 2GiB buffer, growing it is fast, because OS will pass "lazily crated" memory pages. I.e. the actual allocation of memory pages will be deferred until the data is written. So if you allocated a 4GiB buffer, and have only written 2.5GiB it will cost exactly 2.5GiB with granularity of 4Kb (page size). Actually this kind of allocation works starting at about 128K.

>  There's also a potential advantage allowing users to use smaller structures when allowed.

Yes but it costs only +8 bytes (so makes buffer 32 byte in size rather than 24). Just storing additional `tokio_core::ractor::Handle` costs 32 bytes. A `Timeout` structure is 48 bytes, and it also reserves 24 bytes in the heap (queue), and 80 in the slab. I.e. just adding a single timeout for a connection costs 152 bytes. I.e. the cost of 4 buffers of bigger size.

> Would it be worth exploring to see if generics/traits could be used to allow more flexibility, but keeping the runtime cost low?

I don't think it worth it. There is already a `bytes` crate which is overly complex. I wanted to make a simpler alternative.

> Is there a better way to handle a full buffer than to panic? Perhaps return an io::Error, like ErrorKind::InvalidInput or ErrorKind::Other? It looks like a message could be included.

Well, it pollutes code with unneeded cruft. We always do `x.write().unwrap()` when writing to an in-memory buffer, it's already too much.

Basic idea is that when you receiving a message you have an application-defined limit on the size of messages anyway. For example, nginx has `client_max_body_size` and it checks it when `Content-Length` of the request arrived. Your only duty in this case, is to check that `client_max_body_size`  is less than `MAX_BUF_SIZE`. Checking limit again on each write is unnecessary.

**Comment by alreece45** [comment]
Thanks for the insightful-- its was very informative. I'm probably just overthinking a lot of it, especially given how much memory the Tokio stuff uses. 

I suspect there still may be room for something lighter than the bytes crate, but a bit more flexible-- but it'd probably be better to go on actual use-cases/requirements rather than theoreticals.
